In [8]:
import os
import pandas as pd
from dotenv import load_dotenv

In [9]:
load_dotenv()

data_path = os.getenv('SERGIO_DATA_PATH')
files_names = ["All_2010_2017.csv","All_2010_2017_slided.csv","All_2010_2017_slided_withouNaN.csv"]
df_names = ["default","slided","no_nan"]
data = {}

In [10]:
for file, df_name in zip(files_names,df_names):
    full_path = os.path.join(data_path, file)

    df = pd.read_csv(full_path, index_col="t_rec")
    df.index = pd.to_datetime(df.index, format='%Y.%m.%d_%H:%M:%S_TAI')
    df.index.name = "ds"

    data[df_name] = df

In [11]:
data["default"]

                         max_xray class
ds
2010-05-01 00:00:00  7.306500e-08     A
2010-05-01 00:12:00  6.147300e-08     A
2010-05-01 00:24:00  6.775900e-08     A
2010-05-01 00:36:00  6.952600e-08     A
2010-05-01 00:48:00  7.518900e-08     A
...                           ...   ...
2017-12-25 23:12:00  5.619100e-08     A
2017-12-25 23:24:00  5.356700e-08     A
2017-12-25 23:36:00  5.103500e-08     A
2017-12-25 23:48:00  5.387500e-08     A
2017-12-26 00:00:00  5.610000e-08     A

[335521 rows x 2 columns]

In [12]:
data["slided"]

,at0,at1,at2,at3,at4,at5,at6,at7,at8,at9,...,at111,at112,at113,at114,at115,at116,at117,at118,at119,class
ds,,,,,,,,,,,,,,,,,,,,,
2010-05-01 00:00:00,7.306500e-08,6.147300e-08,6.775900e-08,6.952600e-08,7.518900e-08,6.519000e-08,6.485100e-08,1.050100e-07,5.723000e-06,7.471000e-07,...,1.063400e-07,7.058200e-08,6.209200e-08,5.519000e-08,5.467100e-08,5.713700e-08,5.961500e-08,5.809300e-08,5.058900e-08,B
2010-05-01 00:12:00,6.147300e-08,6.775900e-08,6.952600e-08,7.518900e-08,6.519000e-08,6.485100e-08,1.050100e-07,5.723000e-06,7.471000e-07,3.939300e-07,...,7.058200e-08,6.209200e-08,5.519000e-08,5.467100e-08,5.713700e-08,5.961500e-08,5.809300e-08,5.058900e-08,5.672400e-08,B
2010-05-01 00:24:00,6.775900e-08,6.952600e-08,7.518900e-08,6.519000e-08,6.485100e-08,1.050100e-07,5.723000e-06,7.471000e-07,3.939300e-07,2.104900e-07,...,6.209200e-08,5.519000e-08,5.467100e-08,5.713700e-08,5.961500e-08,5.809300e-08,5.058900e-08,5.672400e-08,6.647600e-08,B
2010-05-01 00:36:00,6.952600e-08,7.518900e-08,6.519000e-08,6.485100e-08,1.050100e-07,5.723000e-06,7.471000e-07,3.939300e-07,2.104900e-07,1.186400e-07,...,5.519000e-08,5.467100e-08,5.713700e-08,5.961500e-08,5.809300e-08,5.058900e-08,5.672400e-08,6.647600e-08,8.734800e-08,B
2010-05-01 00:48:00,7.518900e-08,6.519000e-08,6.485100e-08,1.050100e-07,5.723000e-06,7.471000e-07,3.939300e-07,2.104900e-07,1.186400e-07,8.598500e-08,...,5.467100e-08,5.713700e-08,5.961500e-08,5.809300e-08,5.058900e-08,5.672400e-08,6.647600e-08,8.734800e-08,9.439100e-08,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-23 23:24:00,6.935200e-08,7.250000e-08,6.839000e-08,6.623100e-08,6.296900e-08,6.585400e-08,6.351800e-08,6.672900e-08,6.198000e-08,6.387900e-08,...,6.668400e-08,6.623100e-08,6.559800e-08,6.758800e-08,6.840200e-08,6.921600e-08,6.351800e-08,6.594200e-08,6.044200e-08,B
2017-12-23 23:36:00,7.250000e-08,6.839000e-08,6.623100e-08,6.296900e-08,6.585400e-08,6.351800e-08,6.672900e-08,6.198000e-08,6.387900e-08,6.053300e-08,...,6.623100e-08,6.559800e-08,6.758800e-08,6.840200e-08,6.921600e-08,6.351800e-08,6.594200e-08,6.044200e-08,6.209400e-08,B
2017-12-23 23:48:00,6.839000e-08,6.623100e-08,6.296900e-08,6.585400e-08,6.351800e-08,6.672900e-08,6.198000e-08,6.387900e-08,6.053300e-08,8.450400e-08,...,6.559800e-08,6.758800e-08,6.840200e-08,6.921600e-08,6.351800e-08,6.594200e-08,6.044200e-08,6.209400e-08,6.288400e-08,B
2017-12-24 00:00:00,6.623100e-08,6.296900e-08,6.585400e-08,6.351800e-08,6.672900e-08,6.198000e-08,6.387900e-08,6.053300e-08,8.450400e-08,8.034300e-08,...,6.758800e-08,6.840200e-08,6.921600e-08,6.351800e-08,6.594200e-08,6.044200e-08,6.209400e-08,6.288400e-08,6.139500e-08,B
2017-12-24 00:12:00,6.296900e-08,6.585400e-08,6.351800e-08,6.672900e-08,6.198000e-08,6.387900e-08,6.053300e-08,8.450400e-08,8.034300e-08,5.944700e-08,...,6.840200e-08,6.921600e-08,6.351800e-08,6.594200e-08,6.044200e-08,6.209400e-08,6.288400e-08,6.139500e-08,6.384300e-08,B

In [13]:
data["no_nan"]

,id,at0,at1,at2,at3,at4,at5,at6,at7,at8,...,at112,at113,at114,at115,at116,at117,at118,at119,class,mainclass
ds,,,,,,,,,,,,,,,,,,,,,
2010-05-01 19:48:00,100,1.349200e-07,8.828600e-08,6.947000e-08,5.607500e-08,5.501300e-08,5.581000e-08,5.359800e-08,5.156200e-08,5.881800e-08,...,9.342100e-08,9.085500e-08,8.386100e-08,7.477300e-08,8.244500e-08,7.930700e-08,7.306500e-08,7.430400e-08,B,N
2010-05-01 20:00:00,101,8.828600e-08,6.947000e-08,5.607500e-08,5.501300e-08,5.581000e-08,5.359800e-08,5.156200e-08,5.881800e-08,6.048800e-08,...,9.085500e-08,8.386100e-08,7.477300e-08,8.244500e-08,7.930700e-08,7.306500e-08,7.430400e-08,7.631300e-08,B,N
2010-05-01 20:12:00,102,6.947000e-08,5.607500e-08,5.501300e-08,5.581000e-08,5.359800e-08,5.156200e-08,5.881800e-08,6.048800e-08,1.149200e-07,...,8.386100e-08,7.477300e-08,8.244500e-08,7.930700e-08,7.306500e-08,7.430400e-08,7.631300e-08,7.173800e-08,B,N
2010-05-01 20:24:00,103,5.607500e-08,5.501300e-08,5.581000e-08,5.359800e-08,5.156200e-08,5.881800e-08,6.048800e-08,1.149200e-07,1.420900e-07,...,7.477300e-08,8.244500e-08,7.930700e-08,7.306500e-08,7.430400e-08,7.631300e-08,7.173800e-08,7.244600e-08,B,N
2010-05-01 20:36:00,104,5.501300e-08,5.581000e-08,5.359800e-08,5.156200e-08,5.881800e-08,6.048800e-08,1.149200e-07,1.420900e-07,1.063400e-07,...,8.244500e-08,7.930700e-08,7.306500e-08,7.430400e-08,7.631300e-08,7.173800e-08,7.244600e-08,7.421600e-08,B,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-23 18:36:00,332807,7.346800e-08,6.921600e-08,6.410600e-08,6.253200e-08,6.288100e-08,6.234200e-08,6.098500e-08,5.980900e-08,6.331900e-08,...,9.409200e-08,7.274400e-08,7.283500e-08,7.518600e-08,7.328700e-08,7.446300e-08,7.147800e-08,7.943800e-08,B,N
2017-12-23 18:48:00,332808,6.921600e-08,6.410600e-08,6.253200e-08,6.288100e-08,6.234200e-08,6.098500e-08,5.980900e-08,6.331900e-08,9.861500e-08,...,7.274400e-08,7.283500e-08,7.518600e-08,7.328700e-08,7.446300e-08,7.147800e-08,7.943800e-08,7.547300e-08,B,N
2017-12-23 19:00:00,332809,6.410600e-08,6.253200e-08,6.288100e-08,6.234200e-08,6.098500e-08,5.980900e-08,6.331900e-08,9.861500e-08,1.057300e-07,...,7.283500e-08,7.518600e-08,7.328700e-08,7.446300e-08,7.147800e-08,7.943800e-08,7.547300e-08,7.373900e-08,B,N
2017-12-23 19:12:00,332810,6.253200e-08,6.288100e-08,6.234200e-08,6.098500e-08,5.980900e-08,6.331900e-08,9.861500e-08,1.057300e-07,7.265400e-08,...,7.518600e-08,7.328700e-08,7.446300e-08,7.147800e-08,7.943800e-08,7.547300e-08,7.373900e-08,7.609100e-08,B,N
2017-12-23 19:24:00,332811,6.288100e-08,6.234200e-08,6.098500e-08,5.980900e-08,6.331900e-08,9.861500e-08,1.057300e-07,7.265400e-08,6.722600e-08,...,7.328700e-08,7.446300e-08,7.147800e-08,7.943800e-08,7.547300e-08,7.373900e-08,7.609100e-08,7.482500e-08,B,N