## Setup

In [113]:
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv

In [114]:
load_dotenv()

events_csv_path = os.getenv("EVENTS_CSV_PATH")
xrays_csv_path = os.getenv("XRAY_V2_CSV_PATH")
data = {}

begin_year = 1983
end_year = 2024

## Reading CSVs

In [115]:
missing_files = []
for y in range(1983, 1995+1):
    f = missing_files.append(os.path.join(events_csv_path, os.path.join(str(y), f"{y}_events.csv")))
    missing_files.append(os.path.join(events_csv_path, os.path.join(str(y), f"{y}_DSD.csv")))
for y in range(2021, 2024+1):
    missing_files.append(os.path.join(xrays_csv_path, os.path.join(str(y), f"{y}_xrays.csv")))

print(missing_files)

['G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1983\\1983_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1983\\1983_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1984\\1984_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1984\\1984_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1985\\1985_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1985\\1985_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1986\\1986_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1986\\1986_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1987\\1987_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1987\\1987_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1988\\1988_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1988\\1988_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1989\\1989_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1989\\1989_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1990\\1990_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1990\\1990_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1991\\1991_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1991\\1991_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1992\\1992_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1992\\1992_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1993\\1993_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1993\\1993_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1994\\1994_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1994\\1994_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1995\\1995_events.csv', 'G:\\My Drive\\Solar_Flares\\Data\\events\\formatted_csv\\1995\\1995_DSD.csv', 'G:\\My Drive\\Solar_Flares\\Data\\xray_V2\\formatted_csv\\2021\\2021_xrays.csv', 'G:\\My Drive\\Solar_Flares\\Data\\xray_V2\\formatted_csv\\2022\\2022_xrays.csv', 'G:\\My Drive\\Solar_Flares\\Data\\xray_V2\\formatted_csv\\2023\\2023_xrays.csv', 'G:\\My Drive\\Solar_Flares\\Data\\xray_V2\\formatted_csv\\2024\\2024_xrays.csv']

In [116]:
missing_events_dsd = [
    os.path.join(events_csv_path, str(y), f"{y}_{file_type}.csv")
    for y in range(1983, 1995+1)
    for file_type in ('events', 'DSD')
]
missing_xrays = [
    os.path.join(xrays_csv_path, str(y), f"{y}_xrays.csv")
    for y in range(2021, 2024+1)
]
missing_files = set(missing_events_dsd + missing_xrays)

for y in range(begin_year, end_year+1):
    data[y] = {}
    data[y]['events'] = {}
    events_year_dir = os.path.join(events_csv_path, str(y))
    xrays_year_dir = os.path.join(xrays_csv_path, str(y))

    try:
        data[y]['events']['events'] = pd.read_csv(os.path.join(events_year_dir, f"{y}_events.csv"))
    except FileNotFoundError as e:
        if e.filename not in missing_files: print(e)

    try:
        data[y]['events']['DSD'] = pd.read_csv(os.path.join(events_year_dir, f"{y}_DSD.csv"))
    except FileNotFoundError as e:
        if e.filename not in missing_files: print(e)

    try:
        data[y]['xrays'] = pd.read_csv(os.path.join(xrays_year_dir, f"{y}_xrays.csv"))
    except FileNotFoundError as e:
        if e.filename not in missing_files: print(e)

## A

In [117]:
data[2009]['events']['DSD']

,ds,radio_flux_10.7cm,sunspot_number,sunspot_area,new_regions,mean_solar_field,goes_xray_bkgd_flux,flares_c,flares_m,flares_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
0,2009-01-01,69,0,0,0,NaN,A0.0,0,0,0,0,0,0,0
1,2009-01-02,70,0,0,0,NaN,A0.0,0,0,0,0,0,0,0
2,2009-01-03,70,0,0,0,NaN,A0.0,0,0,0,0,0,0,0
3,2009-01-04,69,0,0,0,NaN,A0.0,0,0,0,0,0,0,0
4,2009-01-05,69,0,0,0,NaN,A0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2009-12-27,77,17,0,0,NaN,A2.0,0,0,0,0,0,0,0
361,2009-12-28,76,17,90,0,NaN,A1.4,0,0,0,0,0,0,0
362,2009-12-29,75,17,80,0,NaN,A1.2,0,0,0,0,0,0,0
363,2009-12-30,77,15,50,0,NaN,A1.4,0,0,0,0,0,0,0
364,2009-12-31,80,16,20,0,NaN,A8.5,0,0,0,0,0,0,0

In [118]:
data[2009]['events']['events']

,date,event,begin,max,end,obs,q,type,loc_frq,particulars,reg#
0,2009-01-09,210+,2009-01-09 23:58:00,2009-01-10 00:03:00,2009-01-10 00:05:00,G10,5,XRA,1-8A,B4.0 7.6E-05,1010.0
1,2009-01-10,220+,2009-01-10 00:47:00,2009-01-10 00:51:00,2009-01-10 00:55:00,G10,5,XRA,1-8A,B1.2 4.0E-05,1010.0
2,2009-01-10,230+,2009-01-10 02:33:00,2009-01-10 02:36:00,2009-01-10 02:39:00,G10,5,XRA,1-8A,B1.0 2.3E-05,1010.0
3,2009-01-18,280,2009-01-18 05:03:00,NaN,2009-01-18 05:03:00,LEA,C,RSP,025-059,III/1,NaN
4,2009-01-18,290,2009-01-18 05:04:00,NaN,2009-01-18 05:04:00,CUL,C,RSP,20-90,III/1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
444,2009-12-31,4210,2009-12-31 10:54:00,2009-12-31 10:59:00,2009-12-31 11:06:00,G14,5,XRA,1-8A,B1.6 9.3E-05,NaN
445,2009-12-31,4220,2009-12-31 11:15:00,2009-12-31 11:20:00,2009-12-31 11:31:00,G14,5,XRA,1-8A,B1.9 1.6E-04,NaN
446,2009-12-31,4230,2009-12-31 14:29:00,2009-12-31 14:32:00,2009-12-31 14:51:00,G14,5,XRA,1-8A,B1.3 1.4E-04,NaN
447,2009-12-31,4240,2009-12-31 15:37:00,2009-12-31 15:42:00,2009-12-31 15:46:00,G14,5,XRA,1-8A,B1.5 6.1E-05,NaN
448,2009-12-31,4250,2009-12-31 19:02:00,2009-12-31 19:06:00,2009-12-31 19:10:00,G14,5,XRA,1-8A,B1.8 5.7E-05,NaN

In [119]:
data[1996]['events']['DSD']

,ds,radio_flux_10.7cm,sunspot_number,sunspot_area,new_regions,mean_solar_field,goes_xray_bkgd_flux,flares_c,flares_m,flares_x,flares_optical_s,flares_optical_1,flares_optical_2,flares_optical_3
0,1996-01-01,75.0,25,10,1,NaN,A1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-01-02,75.0,34,0,0,-1.0,A0.8,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,1996-01-03,81.0,30,110,1,NaN,A0.9,1.0,0.0,0.0,NaN,NaN,NaN,NaN
3,1996-01-04,86.0,48,220,1,-1.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN
4,1996-01-05,85.0,69,410,0,6.0,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,1996-12-27,75.0,0,0,0,NaN,A0.8,0.0,0.0,0.0,NaN,NaN,NaN,NaN
362,1996-12-28,74.0,0,0,0,NaN,A0.6,0.0,0.0,0.0,NaN,NaN,NaN,NaN
363,1996-12-29,74.0,0,0,0,NaN,A0.8,0.0,0.0,0.0,NaN,NaN,NaN,NaN
364,1996-12-30,73.0,0,0,0,NaN,A0.8,0.0,0.0,0.0,NaN,NaN,NaN,NaN
365,1996-12-31,72.0,0,0,0,NaN,A0.7,0.0,0.0,0.0,NaN,NaN,NaN,NaN