## Setup

In [1]:
import os
import optuna
import matplotlib.pyplot as plt
from dotenv import load_dotenv
from sklearn.metrics import f1_score, matthews_corrcoef, average_precision_score
import pandas as pd

from src.py_src import util
from src.py_src.models import Specialist910Model

import warnings
pd.options.mode.copy_on_write = False
warnings.filterwarnings("ignore")

In [2]:
load_dotenv()

slided_df_path = os.path.join(os.getenv("XRAY_SLIDED_PATH"), "xray_slided.parquet")
target_class = 'target_class_in_24h'
target_flux = 'target_flux_in_24h'
target_columns = [target_class, target_flux]

buffer_limits = (8.0e-6, 2.0e-5)

df_model_input = util.create_df_model_input_opt(slided_df_path, target_columns, "xl_")

Carregando 68 colunas do arquivo Parquet...

## Preparing Data

In [3]:
specialist_910_pool = df_model_input[df_model_input[target_class] > 2].copy()

train_pct = 0.7
val_pct = (1-train_pct)/2

data = util.prepare_data(
    df_model_input=specialist_910_pool,
    target_class_col=target_class,
    lambda_function=lambda lb: 1 if lb >= 4 else 0,
    train_pct=train_pct,
    val_pct=val_pct,
    target_flux_col=target_flux
)

## Discovery Model

In [4]:
discovery_model = Specialist910Model(
    params={
        'n_estimators': 300,
        'learning_rate': 0.05,
        'max_depth': 5,
        'n_jobs': -1,
        'random_state': 42
    },
    buffer_limits=buffer_limits
)

In [5]:
selected_features = discovery_model.discover_top_features(
    x=data['x']['train'],
    y=data['y']['train'],
    flux_values=data['flux']['train'],
    cumulative_threshold=0.90
)

--- Quick Scan (Discovery Mode) ---
Quick Scan concluído. 40 features selecionadas (de 65).

## Hyperparameter Tuning (Optuna)

In [6]:
def objective(trial):
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'n_estimators': 1000,
        'random_state': 1502,
        'n_jobs': -1,
        'early_stopping_rounds': 50,
        'device': 'cuda',

        'scale_pos_weight': trial.suggest_float("scale_pos_weight", 1.0, 5.0),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'gamma': trial.suggest_float('gamma', 0.1, 5.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10)
    }

    model = Specialist910Model(params=params, buffer_limits=buffer_limits, features_to_keep=selected_features)

    model.fit(
        x=data['x']['train'],
        y=data['y']['train'],
        flux_values=data['flux']['train'],
        eval_set=[(data['x']['val'], data['y']['val'])],
        verbose=False
    )

    y_pred_val = model.predict_proba(data['x']['val'])[:, 1]
    y_pred_class = (y_pred_val >= 0.5).astype(int)

    return matthews_corrcoef(data['y']['val'], y_pred_class)

In [7]:
study = optuna.create_study(direction='maximize')
print("\nIniciando tuning...")
study.optimize(objective, n_trials=50)

print(f"\nBest Score: {study.best_value:.4f}")
best_params = study.best_params

best_params.update({
    'n_estimators': 1000, 'objective': 'binary:logistic',
    'eval_metric': 'logloss', 'random_state': 1502,
    'n_jobs': -1, 'early_stopping_rounds': 50
})

[I 2026-03-18 20:24:55,449] A new study created in memory with name: no-name-b92f3425-de95-4e03-b083-b3c84972b436

Iniciando tuning...

[I 2026-03-18 20:24:56,237] Trial 0 finished with value: 0.2783157776504915 and parameters: {'scale_pos_weight': 3.33704959749282, 'max_depth': 3, 'learning_rate': 0.059867654686485555, 'subsample': 0.8495903854573328, 'colsample_bytree': 0.7229806474181361, 'gamma': 2.4373714808169735, 'min_child_weight': 5}. Best is trial 0 with value: 0.2783157776504915.
[I 2026-03-18 20:24:57,382] Trial 1 finished with value: 0.33895138610472464 and parameters: {'scale_pos_weight': 2.468541367545177, 'max_depth': 7, 'learning_rate': 0.03139449564943395, 'subsample': 0.7590207090490788, 'colsample_bytree': 0.6836282819907287, 'gamma': 4.754348120547804, 'min_child_weight': 7}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:24:58,281] Trial 2 finished with value: 0.3110653510031361 and parameters: {'scale_pos_weight': 2.268079994436102, 'max_depth': 7, 'learning_rate': 0.05846481803480601, 'subsample': 0.8263816873187899, 'colsample_bytree': 0.7427511284706707, 'gamma': 3.9271860804107748, 'min_child_weight': 8}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:24:59,237] Trial 3 finished with value: 0.3319669817301266 and parameters: {'scale_pos_weight': 2.8120873750838866, 'max_depth': 3, 'learning_rate': 0.010947586185462838, 'subsample': 0.7181788322680175, 'colsample_bytree': 0.8333008828527411, 'gamma': 3.6724236128969245, 'min_child_weight': 4}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:00,052] Trial 4 finished with value: 0.2229095102393626 and parameters: {'scale_pos_weight': 1.7602710656974043, 'max_depth': 7, 'learning_rate': 0.18593825568563688, 'subsample': 0.7434736420789725, 'colsample_bytree': 0.7210873175654059, 'gamma': 2.8388400338692446, 'min_child_weight': 2}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:00,979] Trial 5 finished with value: 0.2584351519551303 and parameters: {'scale_pos_weight': 3.9348008204173803, 'max_depth': 6, 'learning_rate': 0.03248944223993542, 'subsample': 0.6745312294970369, 'colsample_bytree': 0.7507400143707376, 'gamma': 3.9984284034019577, 'min_child_weight': 8}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:02,167] Trial 6 finished with value: 0.21724768631068178 and parameters: {'scale_pos_weight': 4.061143857747812, 'max_depth': 8, 'learning_rate': 0.031972387033443406, 'subsample': 0.7301805050502733, 'colsample_bytree': 0.7605580243667628, 'gamma': 2.0729387183332224, 'min_child_weight': 3}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:02,775] Trial 7 finished with value: 0.302772326867747 and parameters: {'scale_pos_weight': 3.102429173241936, 'max_depth': 5, 'learning_rate': 0.1744591548048531, 'subsample': 0.695960343785977, 'colsample_bytree': 0.6698780318176009, 'gamma': 3.2173567540567585, 'min_child_weight': 9}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:03,999] Trial 8 finished with value: 0.18867484201433268 and parameters: {'scale_pos_weight': 3.004602407220174, 'max_depth': 8, 'learning_rate': 0.026868834557567115, 'subsample': 0.7698463234364226, 'colsample_bytree': 0.8392319175570455, 'gamma': 4.874197250564881, 'min_child_weight': 3}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:04,599] Trial 9 finished with value: 0.2143254631393055 and parameters: {'scale_pos_weight': 4.1503529773814645, 'max_depth': 5, 'learning_rate': 0.12244077986532702, 'subsample': 0.7395591785750838, 'colsample_bytree': 0.6541188824345359, 'gamma': 0.1052107678147246, 'min_child_weight': 7}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:06,005] Trial 10 finished with value: 0.3371989492570721 and parameters: {'scale_pos_weight': 1.4145034693687322, 'max_depth': 6, 'learning_rate': 0.014325109359665593, 'subsample': 0.6377978763735869, 'colsample_bytree': 0.6156301241443994, 'gamma': 1.5781380093397657, 'min_child_weight': 10}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:07,743] Trial 11 finished with value: 0.30599388655828713 and parameters: {'scale_pos_weight': 1.0371626108683571, 'max_depth': 6, 'learning_rate': 0.012676708521502225, 'subsample': 0.6293018264388515, 'colsample_bytree': 0.6086345297183302, 'gamma': 0.9840282959512274, 'min_child_weight': 10}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:09,345] Trial 12 finished with value: 0.312807706754857 and parameters: {'scale_pos_weight': 1.3325812840511864, 'max_depth': 7, 'learning_rate': 0.016118030477169743, 'subsample': 0.6004978247781212, 'colsample_bytree': 0.6105184869270397, 'gamma': 1.661208026595132, 'min_child_weight': 6}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:09,986] Trial 13 finished with value: 0.0 and parameters: {'scale_pos_weight': 4.935316684896069, 'max_depth': 4, 'learning_rate': 0.020640349570098596, 'subsample': 0.7931086561897793, 'colsample_bytree': 0.6629587781234115, 'gamma': 1.293935481910633, 'min_child_weight': 10}. Best is trial 1 with value: 0.33895138610472464.
[I 2026-03-18 20:25:10,865] Trial 14 finished with value: 0.3428298795065013 and parameters: {'scale_pos_weight': 2.058340040181004, 'max_depth': 6, 'learning_rate': 0.044690837069244996, 'subsample': 0.6506571911606713, 'colsample_bytree': 0.6941705155032176, 'gamma': 0.6449201840373446, 'min_child_weight': 6}. Best is trial 14 with value: 0.3428298795065013.
[I 2026-03-18 20:25:11,889] Trial 15 finished with value: 0.2586657399972878 and parameters: {'scale_pos_weight': 2.1608861116437166, 'max_depth': 7, 'learning_rate': 0.05093215453135249, 'subsample': 0.8806498433451398, 'colsample_bytree': 0.7913755235013168, 'gamma': 4.827913735349776, 'min_child_weight': 6}. Best is trial 14 with value: 0.3428298795065013.
[I 2026-03-18 20:25:12,583] Trial 16 finished with value: 0.33515555710346506 and parameters: {'scale_pos_weight': 2.387836314806357, 'max_depth': 5, 'learning_rate': 0.08253140118299329, 'subsample': 0.672169256551561, 'colsample_bytree': 0.6862496487132237, 'gamma': 0.15568530912813427, 'min_child_weight': 5}. Best is trial 14 with value: 0.3428298795065013.
[I 2026-03-18 20:25:13,908] Trial 17 finished with value: 0.30429234490540535 and parameters: {'scale_pos_weight': 1.8217791719221859, 'max_depth': 8, 'learning_rate': 0.04022153212614966, 'subsample': 0.7982012439398055, 'colsample_bytree': 0.6959439876548597, 'gamma': 0.6272463032724049, 'min_child_weight': 7}. Best is trial 14 with value: 0.3428298795065013.
[I 2026-03-18 20:25:14,506] Trial 18 finished with value: 0.3535159979168062 and parameters: {'scale_pos_weight': 2.764995118697141, 'max_depth': 4, 'learning_rate': 0.08468441351127037, 'subsample': 0.7739196444630587, 'colsample_bytree': 0.8835148964143094, 'gamma': 4.373982844248727, 'min_child_weight': 1}. Best is trial 18 with value: 0.3535159979168062.
[I 2026-03-18 20:25:15,128] Trial 19 finished with value: 0.25838643171240677 and parameters: {'scale_pos_weight': 3.552753459090975, 'max_depth': 4, 'learning_rate': 0.0876077400367204, 'subsample': 0.698838380441458, 'colsample_bytree': 0.8852385256659079, 'gamma': 3.0773110735122886, 'min_child_weight': 1}. Best is trial 18 with value: 0.3535159979168062.
[I 2026-03-18 20:25:15,711] Trial 20 finished with value: 0.3439641418505841 and parameters: {'scale_pos_weight': 2.701607721972029, 'max_depth': 4, 'learning_rate': 0.0927045103114762, 'subsample': 0.784441796516846, 'colsample_bytree': 0.8913006633456874, 'gamma': 2.2338903296612633, 'min_child_weight': 1}. Best is trial 18 with value: 0.3535159979168062.
[I 2026-03-18 20:25:16,330] Trial 21 finished with value: 0.3287985823155028 and parameters: {'scale_pos_weight': 2.6425468290850445, 'max_depth': 4, 'learning_rate': 0.08447528642299373, 'subsample': 0.7976193958735558, 'colsample_bytree': 0.8999168182209684, 'gamma': 2.456769838041505, 'min_child_weight': 1}. Best is trial 18 with value: 0.3535159979168062.
[I 2026-03-18 20:25:16,919] Trial 22 finished with value: 0.36233532951912406 and parameters: {'scale_pos_weight': 1.9463899276141308, 'max_depth': 4, 'learning_rate': 0.1202915904886065, 'subsample': 0.8310355292827527, 'colsample_bytree': 0.8610654754306827, 'gamma': 1.9708993478092423, 'min_child_weight': 2}. Best is trial 22 with value: 0.36233532951912406.
[I 2026-03-18 20:25:17,497] Trial 23 finished with value: 0.32572747835173715 and parameters: {'scale_pos_weight': 2.7333774033403397, 'max_depth': 4, 'learning_rate': 0.12779996322687637, 'subsample': 0.8371155966262742, 'colsample_bytree': 0.8615077521961851, 'gamma': 2.1331003692982407, 'min_child_weight': 2}. Best is trial 22 with value: 0.36233532951912406.
[I 2026-03-18 20:25:18,045] Trial 24 finished with value: 0.38333090277937687 and parameters: {'scale_pos_weight': 1.8747744427336466, 'max_depth': 3, 'learning_rate': 0.11831591659108928, 'subsample': 0.8974572646208138, 'colsample_bytree': 0.8129164664010781, 'gamma': 2.09366725488412, 'min_child_weight': 2}. Best is trial 24 with value: 0.38333090277937687.
[I 2026-03-18 20:25:18,629] Trial 25 finished with value: 0.37037323291209345 and parameters: {'scale_pos_weight': 1.8203680036144092, 'max_depth': 3, 'learning_rate': 0.12857436787087176, 'subsample': 0.8879562461686402, 'colsample_bytree': 0.8015885825876832, 'gamma': 1.7794083224958375, 'min_child_weight': 2}. Best is trial 24 with value: 0.38333090277937687.
[I 2026-03-18 20:25:19,216] Trial 26 finished with value: 0.40214247799502834 and parameters: {'scale_pos_weight': 1.6250602011209356, 'max_depth': 3, 'learning_rate': 0.13412860307871705, 'subsample': 0.8927759629561637, 'colsample_bytree': 0.8045744089930934, 'gamma': 1.8094905732792328, 'min_child_weight': 3}. Best is trial 26 with value: 0.40214247799502834.
[I 2026-03-18 20:25:19,746] Trial 27 finished with value: 0.4248853373656811 and parameters: {'scale_pos_weight': 1.5165014107618593, 'max_depth': 3, 'learning_rate': 0.1941406186307742, 'subsample': 0.8934711638849322, 'colsample_bytree': 0.7952295097942736, 'gamma': 1.649540356794427, 'min_child_weight': 3}. Best is trial 27 with value: 0.4248853373656811.
[I 2026-03-18 20:25:20,330] Trial 28 finished with value: 0.39879722570307446 and parameters: {'scale_pos_weight': 1.5034146493478626, 'max_depth': 3, 'learning_rate': 0.15923532215237649, 'subsample': 0.8644784268709356, 'colsample_bytree': 0.7916126162035874, 'gamma': 1.3336460510954151, 'min_child_weight': 4}. Best is trial 27 with value: 0.4248853373656811.
[I 2026-03-18 20:25:20,951] Trial 29 finished with value: 0.3890771389870267 and parameters: {'scale_pos_weight': 1.4785799880565955, 'max_depth': 3, 'learning_rate': 0.16959269961720438, 'subsample': 0.8641958096822004, 'colsample_bytree': 0.7646124031703803, 'gamma': 1.2960377259818316, 'min_child_weight': 4}. Best is trial 27 with value: 0.4248853373656811.
[I 2026-03-18 20:25:21,491] Trial 30 finished with value: 0.427116100295124 and parameters: {'scale_pos_weight': 1.0084344097157139, 'max_depth': 3, 'learning_rate': 0.19975138605868253, 'subsample': 0.8616969163610054, 'colsample_bytree': 0.7771263936402458, 'gamma': 1.3076925012906546, 'min_child_weight': 4}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:22,112] Trial 31 finished with value: 0.40324838338979013 and parameters: {'scale_pos_weight': 1.0501742571464991, 'max_depth': 3, 'learning_rate': 0.15192798483899186, 'subsample': 0.8639565816329424, 'colsample_bytree': 0.7828347419417976, 'gamma': 1.3153737579570983, 'min_child_weight': 4}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:22,710] Trial 32 finished with value: 0.40228840994840237 and parameters: {'scale_pos_weight': 1.0870675562137635, 'max_depth': 3, 'learning_rate': 0.14589204576752873, 'subsample': 0.8641561499464161, 'colsample_bytree': 0.7772162689398516, 'gamma': 0.817626840607922, 'min_child_weight': 3}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:23,306] Trial 33 finished with value: 0.4060942632683653 and parameters: {'scale_pos_weight': 1.0383911650134714, 'max_depth': 3, 'learning_rate': 0.1888804345547822, 'subsample': 0.8570966773480552, 'colsample_bytree': 0.7726485442514799, 'gamma': 0.8530769014267007, 'min_child_weight': 4}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:23,856] Trial 34 finished with value: 0.41677014828652964 and parameters: {'scale_pos_weight': 1.1736338346126285, 'max_depth': 3, 'learning_rate': 0.19988568825753134, 'subsample': 0.8129034433165805, 'colsample_bytree': 0.7230752196519824, 'gamma': 0.9719884578503919, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:24,433] Trial 35 finished with value: 0.4171850337644693 and parameters: {'scale_pos_weight': 1.2375495281871673, 'max_depth': 3, 'learning_rate': 0.19326608928836905, 'subsample': 0.8186387272600573, 'colsample_bytree': 0.7247339483244817, 'gamma': 0.3323059290565582, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:25,012] Trial 36 finished with value: 0.403234221637362 and parameters: {'scale_pos_weight': 1.2751923302200694, 'max_depth': 3, 'learning_rate': 0.19199443951944134, 'subsample': 0.8129150443352315, 'colsample_bytree': 0.7260280755349587, 'gamma': 0.3985855056905505, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:25,750] Trial 37 finished with value: 0.35870045816696405 and parameters: {'scale_pos_weight': 1.2826182591511612, 'max_depth': 4, 'learning_rate': 0.06638733720982709, 'subsample': 0.8182452953021666, 'colsample_bytree': 0.7329762975215799, 'gamma': 1.031841492892521, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:26,341] Trial 38 finished with value: 0.38982920569097873 and parameters: {'scale_pos_weight': 1.6224290367809389, 'max_depth': 3, 'learning_rate': 0.10698446331609926, 'subsample': 0.84098183088826, 'colsample_bytree': 0.7150388781933474, 'gamma': 1.5553638274540176, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:26,973] Trial 39 finished with value: 0.2992274551078709 and parameters: {'scale_pos_weight': 1.2453787681853004, 'max_depth': 5, 'learning_rate': 0.1985707787754923, 'subsample': 0.8798852080730015, 'colsample_bytree': 0.7458470879713951, 'gamma': 0.4328302209676751, 'min_child_weight': 4}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:27,580] Trial 40 finished with value: 0.39894633074242125 and parameters: {'scale_pos_weight': 1.6255908281761027, 'max_depth': 3, 'learning_rate': 0.1553172509519148, 'subsample': 0.8478259354852017, 'colsample_bytree': 0.7076112350474585, 'gamma': 1.0737596046593165, 'min_child_weight': 6}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:28,196] Trial 41 finished with value: 0.3963315588508738 and parameters: {'scale_pos_weight': 1.0002932213643532, 'max_depth': 3, 'learning_rate': 0.19963374160642564, 'subsample': 0.81560228143136, 'colsample_bytree': 0.8246700208421098, 'gamma': 0.7949468564678623, 'min_child_weight': 4}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:28,777] Trial 42 finished with value: 0.41519840948400705 and parameters: {'scale_pos_weight': 1.2096681606380248, 'max_depth': 3, 'learning_rate': 0.17311876894608486, 'subsample': 0.8518042585234047, 'colsample_bytree': 0.7669285941156493, 'gamma': 0.3834051908888013, 'min_child_weight': 3}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:29,414] Trial 43 finished with value: 0.4158232515056346 and parameters: {'scale_pos_weight': 1.263128465586, 'max_depth': 3, 'learning_rate': 0.10518770011973251, 'subsample': 0.8776172268257785, 'colsample_bytree': 0.7558730844184908, 'gamma': 0.34728734502986036, 'min_child_weight': 3}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:30,014] Trial 44 finished with value: 0.3559498863800105 and parameters: {'scale_pos_weight': 1.5308488880014264, 'max_depth': 4, 'learning_rate': 0.1446128376053004, 'subsample': 0.879134478739943, 'colsample_bytree': 0.7489858187260875, 'gamma': 0.5976780774037923, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:30,651] Trial 45 finished with value: 0.39524601839111484 and parameters: {'scale_pos_weight': 1.344021399380915, 'max_depth': 3, 'learning_rate': 0.10221300881688564, 'subsample': 0.7525687524459966, 'colsample_bytree': 0.7363182297934774, 'gamma': 0.17278139944746712, 'min_child_weight': 3}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:31,307] Trial 46 finished with value: 0.358476144232835 and parameters: {'scale_pos_weight': 2.2523176305468904, 'max_depth': 4, 'learning_rate': 0.06490355964438396, 'subsample': 0.8998365891561824, 'colsample_bytree': 0.7557302257754751, 'gamma': 1.1216101555118427, 'min_child_weight': 3}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:31,878] Trial 47 finished with value: 0.39874820700629326 and parameters: {'scale_pos_weight': 1.701344321348145, 'max_depth': 3, 'learning_rate': 0.17327453556290118, 'subsample': 0.8270717541755772, 'colsample_bytree': 0.7167084991317563, 'gamma': 2.763098450507248, 'min_child_weight': 5}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:32,462] Trial 48 finished with value: 0.251770051388384 and parameters: {'scale_pos_weight': 3.2945453841354366, 'max_depth': 4, 'learning_rate': 0.09973933784386704, 'subsample': 0.8799701492516675, 'colsample_bytree': 0.8270069799774461, 'gamma': 0.30397731459083704, 'min_child_weight': 8}. Best is trial 30 with value: 0.427116100295124.
[I 2026-03-18 20:25:33,073] Trial 49 finished with value: 0.0 and parameters: {'scale_pos_weight': 4.891572743861968, 'max_depth': 5, 'learning_rate': 0.1410001831172451, 'subsample': 0.8448775688926075, 'colsample_bytree': 0.6359843255879678, 'gamma': 1.4963733148478289, 'min_child_weight': 6}. Best is trial 30 with value: 0.427116100295124.

Best Score: 0.4271

In [8]:
final_model = Specialist910Model(params=study.best_params, buffer_limits=buffer_limits, features_to_keep=selected_features)
final_model.fit(
    x=data['x']['train'], y=data['y']['train'],
    flux_values=data['flux']['train']
)

Specialist910Model(buffer_limits=None,
                   features_to_keep=['Edec', 'xl_mean_12h', 'xl_log_mean_6h',
                                     'xl_log_mean_1h', 'xl_max_1h',
                                     'xl_integ_6h', 'sum_class_score_6h',
                                     'sum_class_score_24h', 'xl_std_7D',
                                     'xl_max_7D', 'xl_integ_7D', 'xl_max_24h',
                                     'sum_class_score_3D', 'Mdec', 'count_C_7D',
                                     'Xdec', 'xl_log_mean_24h', 'count_X_7D',
                                     'sum_class_score_7D', 'xl_integ_24h',
                                     'xl_...h', 'count_M_7D',
                                     'xl_ratio_max1h_mean24h', 'xl_mean_7D',
                                     'xl_log_mean_7D', 'xl_std_1h',
                                     'count_C_3D', 'xl_integ_1h', 'Cdec',
                                     'xl_mean_24h', ...],
                   params={'colsample_bytree': 0.7771263936402458,
                           'gamma': 1.3076925012906546,
                           'learning_rate': 0.19975138605868253, 'max_depth': 3,
                           'min_child_weight': 4,
                           'scale_pos_weight': 1.0084344097157139,
                           'subsample': 0.8616969163610054})

## Threshold Tuning

In [9]:
fig = final_model.get_threshold_graph(data['x']['test'], data['y']['test'])
plt.show()

In [10]:
final_model.optimize_threshold(data['x']['test'], data['y']['test'])

Threshold de Equilíbrio (P=R): 0.4597

np.float32(0.459716)

## Results

In [11]:
print(final_model.get_classification_report(
    data['x']['test'], data['y']['test'], target_names=['C', 'MX']
))

              precision    recall  f1-score   support

           C       0.48      0.48      0.48     18946
          MX       0.71      0.71      0.71     33611

    accuracy                           0.63     52557
   macro avg       0.60      0.60      0.60     52557
weighted avg       0.63      0.63      0.63     52557

In [12]:
fig, summary = final_model.analyze_flux_errors(
    data['x']['test'], data['y']['test'],
    flux_values=data['flux']['test'],
    buffer_limits=buffer_limits
)
display(summary)
plt.show()

Outcome,TN (Correct Rejection),FP (False Alarm),FP Rate (%),TP (Hit),FN (Miss),FN Rate (%)
Zone,,,,,,
1. Safe/Low Zone,8257,7186,46.5,0,0,NaN
2. Buffer/Transition Zone,925,2578,73.6,8781,3308,27.4
3. Danger/High Zone,0,0,NaN,15066,6456,30.0

In [13]:
error_report = final_model.analyze_error_distribution(
    x=data['x']['test'],
    y_true=data['y']['test'],
    flux_values=data['flux']['test']
)
display(error_report)

,FN (Miss),FP (False Alarm),FN (Miss) Avg Flux,FP (False Alarm) Avg Flux
SolarClass,,,,
C (1.0 - 9.9),15,9764,9.00e-06,6.08e-06
M (1.0 - 9.9),8339,0,3.32e-05,-
X (> M10),1410,0,3.01e-04,-

In [14]:
x_test = data['x']['test']
y_persistence = ((x_test['count_M_24h'] > 0) | (x_test['count_X_24h'] > 0)).astype(int).values

y_pred = final_model.predict(x_test)

In [15]:
metrics_df = final_model.get_comprehensive_metrics(data['x']['test'], data['y']['test'])
print("--- Métricas Globais (TSS, HSS, MCC, AUCs) ---")
display(metrics_df)

--- Métricas Globais (TSS, HSS, MCC, AUCs) ---

      TSS     HSS     MCC  ROC AUC  PR AUC  F1 Score
0  0.1941  0.1941  0.1941   0.6385   0.746    0.7095

In [ ]:
pr_f1 = final_model.calculate_prss(data['y']['test'], y_pred, y_persistence)
print(f"\nPersistence Relative F1 (PR-F1): {pr_f1:.4f}  | (Acima de 0 significa que o modelo bate o baseline)")

In [ ]:
ac_nc_df = final_model.analyze_ac_nc_performance(x_test, data['y']['test'], y_persistence)
print("\n--- Performance em Transições de Estado (AC) vs Estados Estáveis (NC) ---")
display(ac_nc_df)

## Features Importance

In [ ]:
features_importance = final_model.get_feature_importance()
features_importance

## Export

In [ ]:
specialist_910_dir = os.getenv('SPECIALIST_910_MODELS_PATH')
save_path = os.path.join(specialist_910_dir, '24h/specialist_910_24h_v1.joblib')
final_model.save(save_path)